config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'posts#index'

  resources :posts ,except: [:show] do
    post '/like', to: "likes#like_toggle"
    resources :comments, only: [:create, :destroy]
  end
  resources :follows, only: [:create, :destroy]
  get '/followers' => 'posts#followers'
  get '/followings' => 'posts#followings'
  get 'likedusers/:id'=> 'posts#likedusers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower , class_name: "User"
  belongs_to :followed , class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments
  # 나의 추종자
  has_many :follower_relations, foreign_key: "followed_id", class_name: "Follow"
  has_many :followers, through: :follower_relations, source: :follower
  # 내가 추종한 사람
  has_many :following_relations, foreign_key: "follower_id", class_name: "Follow"
  has_many :followings, through: :following_relations, source: :followed



  def is_like?(post)
    Like.find_by(user_id: self.id, post_id: post.id).present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_ownership!, only: [:destroy]
  def create
    new_comment = Comment.new(content:params[:content],
                              post_id:params[:post_id],
                              user_id:current_user.id)
    new_comment.save
    redirect_to :back
  end
  def destroy
    @comment.destroy
    redirect_to :back
  end

  private

  def check_ownership!
    @comment = Comment.find(params[:id])
    redirect_to root_path if @comment.user.id != current_user.id
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    Follow.create(followed_id: params[:followed_id],
                      follower_id:current_user.id)
    redirect_to :back
  end

  def destroy
    Follow.find_by(followed_id: params[:id],
                   follower_id: current_user.id).destroy
    redirect_to :back
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def like_toggle
    like = Like.find_by(user_id:current_user.id, post_id: params[:post_id])
    if like.nil?
      Like.create(user_id: current_user.id,post_id: params[:post_id])
    else
      like.destroy
    end
      redirect_to :back

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_ownership, only: [:edit, :update, :destroy]

  def index

    @posts = Post.all.order('created_at desc')
    @posts_count = current_user.posts.length
  end

  def new

  end
  def create
    new_post = Post.new(user_id:current_user.id, content: params[:content])
    if new_post.save
      redirect_to '/'
    else
      redirect_to 'new_post_path'
    end
  end
  def edit
    @post=Post.find(params[:id])
  end
  def update
    @post.content = params[:content]
    if @post.save
      redirect_to '/'
    else
      render "edit"
    end
  end
  def destroy
    @post.destroy
    redirect_to '/'
  end
  def followers

  end

  def followings

  end
  def likedusers
    @post=Post.find(params[:id])

  end


  private

  def check_ownership
    @post = Post.find_by(id:params[:id])
    redirect_to root_path unless @post.user_id == current_user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SNS2</title>
    <%= csrf_meta_tags %>
    <!--Import Google Icon Font-->
    <link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
  <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo">HELLO</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="/posts">Posts</a></li>
        <%if user_signed_in?%>
        <li><%=link_to "sign out",destroy_user_session_path, method:"delete", data: {confirm:"로그아웃 하시겠습니까?"}%></li>
        <li><a href="/users/edit"><%=current_user.name%></a></li>
        <%else%>
        <li><a href="/users/sign_in">sign in</a></li>
        <li><a href="/users/sign_up">sign up</a></li>
        <%end%>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><a href="/posts">Posts</a></li>
        <%if user_signed_in?%>
            <li><a href="/users/sign_out",data-method="delete">sign out</a></li>
        <%else%>
            <li><a href="/users/sign_in">sign in</a></li>
            <li><a href="/users/sign_up">sign up</a></li>
        <%end%></ul>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="card">
  <div class="card-content">
    <span class="card-title"><%= post.user.name %></span>
      <%if user_signed_in? && current_user.id != post.user.id%>
        <%if current_user.followings.include?(post.user)%>
          <%=form_tag follow_path(post.user.id) ,method: :delete, class: "right" do%>
          <button class="btn">팔로우 취소</button>
          <% end %>
        <%else%>
          <%=form_tag follows_path, method: "post", class: "right" do%>
          <input type="hidden" name="followed_id" value="<%=post.user.id%>">
          <button class="btn">팔로우</button>
          <% end %>
        <%end%>
      <%end%>
    <span><%= post.created_at %></span>
    <p class="pre-line"><%= post.content %></p>
  </div>

  <div class="card-action">
    <a href="/likedusers/<%=post.id%>" style="margin-right:0px"><%=post.likes.size%></a> 명이 좋아합니다.
    <% if current_user.is_like?(post) %>
    <%=link_to "좋아요 취소", post_like_path(post),method: :post%>
    <%else%>
    <%=link_to "좋아요", post_like_path(post), method: :post%>
    <%end%>

    <%if current_user.id == post.user_id%>
        <%=link_to "수정" ,edit_post_path(post), class: "right"%>
        <%=link_to "삭제" ,post_path(post), class: "right", method: :delete%>
    <% end %>
    <%= form_tag post_comments_path(post) do %>
        <div class="input-field">
          <%= text_area_tag :content, nil, class: "materialize-textarea", placeholder: "댓글을 작성해주세요.", required: true %>
        </div>
        <div class="input-field">
          <%= button_tag "댓글 쓰기", class: "btn" %>
        </div>
    <% end %>
    <% if post.comments.present? %>
        <ul class="collection">
          <% post.comments.each do |comment| %>
              <li class="collection-item">
                <span class="title"><%= comment.user.name %></span>
                <span class="right"><%= comment.created_at %></span>
                <p><%= comment.content %></p>
                <% if comment.user.id == current_user.id %>
                    <div><%= link_to "삭제", post_comment_path(post, comment), method: "delete" %></div>
                <% end %>
              </li>
          <% end %>
        </ul>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="card col s12">
      <div class="card-content">
        <div class="card-title">수정하기</div>
        <%= form_tag post_path(@post),method: "patch" do  %>
            <input type="hidden" name="id" value="<%=@post.id%>" >
            <div class="input-field">
              <%= text_area_tag :content, @post.content, class: "materialize-textarea", placeholder: "무슨 생각을 하고 있나요?" %>
            </div>

            <div class="input-field">
              <%= button_tag "수정하기", class: "btn" %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/followers.html.erb
<style>
  h2{
    text-align:center;
    font-family: Arial;
    colof:red;
  }
</style>
<div class="container">
  <h2><%=current_user.name%>의 팔로워</h2>
    <% current_user.followers.each do |f|%>
    <p><%=f.name%></p>
    <%end%>
  <a href="/" class="btn right">돌아가기</a>
</div>

app/views/posts/followings.html.erb
<style>
  h2{
    text-align:center;
    text-colof:red;
  }
</style>
<div class="container">
  <h2><%=current_user.name%>의 팔로잉</h2>
    <% current_user.followings.each do |f|%>
      <p><%=f.name%></p>
    <%end%>
  <a href="/" class="btn right">돌아가기</a>

</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 m4">
      <div class="card">
        <div class="card-image">
          <img src="http://materializecss.com/images/office.jpg" />
        </div>
        <div class="card-content">
          <div class="card-title"><%= current_user.name %></div>
          <p>이메일 : <%= current_user.email %></p>
          <p>올린 글 개수 : <%= @posts_count %></p>
          <p>팔로워 : <a href="/followers"><%=current_user.followers.length%></a></p>
          <p>팔로잉 : <a href="/followings"><%=current_user.followings.length%></a></p>
          <%= link_to new_post_path do %>
              <button class="btn">글 쓰기</button>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col s12 m8">
      <% current_user.followings.each do |f|%>
      <% f.posts.each do |post| %>
          <%= render partial: "post", object: post %>
      <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/likedusers.html.erb
<style>
  h2{
    text-align:center;
    font-family: Arial;
    color:blue;
  }
</style>
<div class="container">
  <h2>좋아요 한 사람</h2>
  <% @post.liked_users.each do |u|%>
    <%=u.name%>
  <% end %>
  <a href="/" class="btn right">돌아가기</a>


</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="card col s12">
      <div class="card-content">
        <div class="card-title">새 글 작성하기</div>
        <%= form_tag posts_path do  %>
            <div class="input-field">
              <%= text_area_tag :content, nil, class: "materialize-textarea", placeholder: "무슨 생각을 하고 있나요?" %>
            </div>

            <div class="input-field">
              <%= button_tag "작성하기", class: "btn" %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>